export const URL_PATHS = {
  LINK: '/payments',
  LANDING_PAGE: '/landing-page',
  CATALOGUE: '/catalogue',
  PORTAL: '/enrollment',
  QR: '/qr',
  REVERSETX: '/reversetx',
  PORTAL_INICIO: '/enrollment/inicio',
  PORTAL_LOGIN: '/enrollment/login',
  PORTAL_REGISTER: '/enrollment/register',
  PORTAL_USER_AVAL: '/enrollment/registro-aval',
  PORTAL_LOGIN_OTP: '/enrollment/validar-usuario',
  PORTAL_FORGOT: '/enrollment/olvido-contraseña',
  REPORTS_DASHBOARD: '/dashboard',
  ACCOUNT_SELECTION: '/account-selection',
  PRODUCT_BOND: '/bond-aggregator',
  PRODUCT_BOND_GATEWAY: '/bond-gateway',
  HOME: '/',
  BUSSINNES: '/negocio',
  PRODUCTS: '/productos',
  COST: '/cuanto-cuesta',
  SECURITY: '/tips-de-seguridad',
  HELP: '/ayuda',
  SITEMAP: '/sitemap',
  LAUNCH: '/lanzamiento',
  VALIDATOR: '/validador',
  UPDATE_BROWSER: '/actualiza-tu-navegador'
};
